spring:
  application:
    name: socialbooks
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socialbooksDB?createDatabaseIfNotExist=true&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

server:
  port: 8081

swagger:
  title: SocialBooks
  description: Social books APIs.
  contact:
    name: Rafael De Pieri Barbosa
    url: socialbooks.com
    email: email@socialbooks.com
  version: 1.0.0