spring:
  application:
    name: socialbooks
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socialbooksDB?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true

swagger:
  title: SocialBooks
  description: Social books APIs.
  contact:
    name: Rafael De Pieri Barbosa
    url: socialbooks.com
    email: email@socialbooks.com
  version: 1.0.0